--- #YAML:1.0
name:               File-Fingerprint-Huge
version:            1.3
abstract:           Very large file high speed finger printing and checksuming
author:
    - Colin Faber <cfaber@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
